name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check affected packages
        run: pnpm turbo run check --affected
        env:
          TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test affected packages
        run: pnpm turbo run test --affected
        env:
          TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
